#!/bin/bash /usr/lib/turtle/turtle_module
VERSION="1.0"
DESCRIPTION="System Uptime"
CONF=/tmp/uptime.form

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}

function configure {
  dialog --title "Uptime" --msgbox "\n\
(\___/) \n\
(='.'=)    $(date)\n\
(\")_(\")    $(uptime)\n\
" 9 72
}

function start {
  uptime
  uptime >> /tmp/uptime.log
}
function stop {
  uptime
}
function status {
 echo 0
}
